version: '3.8'

volumes:
  dev_postgres_data:

networks:
  default:
    name: test_service_dev_network

services:
  dev_web:
    container_name: test_service_dev_web_container
    build: ../backend
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py initadmin
      && python manage.py collectstatic --no-input --clear
      && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ../backend/:/app/
    expose:
      - 8000
    ports:
      - "8000:8000"

    env_file:
      - ../backend/.env.dev/.env.dev.settings
    depends_on:
      - dev_db
    entrypoint: ./scripts/wait_db.sh


  dev_db:
    container_name: test_service_dev_db_container
    image: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../backend/.env.dev/.env.dev.db

  dev_redis:
    container_name: test_service_dev_redis_container
    image: redis:alpine


  dev_celery:
    container_name: test_service_dev_celery_container
    restart: always
    build: ../backend
    command: celery -A conf worker -B -l info
    env_file:
      - ../backend/.env.dev/.env.dev.settings
      - ../backend/.env.dev/.env.dev.celery
    volumes:
      - ../backend/:/app/
    depends_on:
      - dev_db
      - dev_redis
      - dev_web