# Generated by Django 4.1.2 on 2022-12-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('title', 'question')},
        ),
    ]
